blueprints/entries/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import TextAreaField, SubmitField, StringField
from wtforms.validators import DataRequired, length


class CreateEntryForm(FlaskForm):
    description = TextAreaField('Description', validators=[DataRequired(), length(1, -1)])
    submit = SubmitField('Create')


class EditEntryForm(FlaskForm):
    description = TextAreaField('Description', validators=[DataRequired(), length(1, -1)])
    submit = SubmitField('Save')


class CreateCommentForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), length(1, 32)])
    content = TextAreaField('Content', validators=[DataRequired(), length(1, -1)])
    submit = SubmitField('Create')

app.py
from flask import Flask

import persistence
import blueprints.pages
import blueprints.entries
from config import Config


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    persistence.init_app(app)

    app.register_blueprint(blueprints.pages.bp, url_prefix='/')
    app.register_blueprint(blueprints.entries.bp, url_prefix='/entries')

    return app


if __name__ == '__main__':
    create_app().run()

blueprints/entries/__init__.py
from flask import Blueprint

bp = Blueprint('entries', __name__)

from blueprints.entries import routes

blueprints/entries/routes.py
from flask import request, render_template, abort, flash, redirect, url_for

from persistence.model.comment import Comment
from blueprints.entries import bp
from blueprints.entries.forms import CreateEntryForm, EditEntryForm
from blueprints.entries.forms import CreateCommentForm
from persistence.repository.comment import CommentRepository
from persistence.model.entry import Entry
from persistence.repository.entry import EntryRepository


@bp.route('/')
def list_all():
    if request.args.get('search'):
        entries = EntryRepository.find_by_day(request.args.get('search'))
    else:
        entries = EntryRepository.find_all()

    return render_template('entries/list.html', entries=entries)


@bp.route('/view/<int:entry_id>', methods=('GET', 'POST'))
def view(entry_id):
    entry = EntryRepository.find_by_id(entry_id) or abort(404)
    comment_form = CreateCommentForm()

    if comment_form.validate_on_submit():
        comment = Comment()
        comment.entry_id = entry_id # TODO kérdés, ez így jó?
        comment.form_update(comment_form)

        try:
            comment_form.process()
            CommentRepository.save(comment)
            flash("Comment created.")

        except Exception as err:
            flash(str(err))

    return render_template('entries/view.html', entry=entry, comment_form=comment_form)


@bp.route('/create', methods=('GET', 'POST'))
def create():
    entry = Entry()
    form = CreateEntryForm()

    if form.validate_on_submit():
        entry.form_update(form)

        try:
            EntryRepository.save(entry)
            flash('Entry created.')

            return redirect(url_for('entries.list_all'))
        except Exception as err:
            flash(str(err))

    return render_template('entries/form.html', form=form, create=True)


@bp.route('/edit/<int:entry_id>', methods=('GET', 'POST'))
def edit(entry_id):
    entry = EntryRepository.find_by_id(entry_id) or abort(404)
    form = EditEntryForm(obj=entry)

    if form.validate_on_submit():
        entry.form_update(form)

        try:
            EntryRepository.save(entry)
            flash('Entry saved.')

            return redirect(url_for('entries.edit', entry_id=entry.id))
        except Exception as err:
            flash(str(err))

    return render_template('entries/form.html', form=form)


@bp.route('/delete/<int:entry_id>', methods=('POST',))
def delete(entry_id):
    entry = EntryRepository.find_by_id(entry_id) or abort(404)

    try:
        EntryRepository.delete(entry)
        flash('Entry deleted.')
    except Exception as err:
        flash(str(err))

    return redirect(url_for('entries.list_all'))

blueprints/pages/__init__.py
from flask import Blueprint

bp = Blueprint('pages', __name__)

from blueprints.pages import routes

blueprints/pages/routes.py
from flask import render_template

from blueprints.pages import bp


@bp.route('/')
def home():
    return render_template('pages/home.html')

persistence/__init__.py
import click
from alchemical.flask import Alchemical
from flask import g

db = Alchemical()


def init_app(app):
    app.cli.add_command(__install_command)
    app.before_request(__on_before_request)
    app.teardown_appcontext(__on_teardown_appcontext)

    db.init_app(app)


def install():
    db.drop_all()
    db.create_all()


@click.command('install')
def __install_command():
    install()
    click.echo('Application installation successful.')


def __on_before_request():
    if 'session' not in g:
        g.session = db.Session()


def __on_teardown_appcontext(e):
    if 'session' in g:
        g.pop('session').close()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>

<main>
    <h1>{% block heading %}{% endblock %}</h1>

    {% with messages = get_flashed_messages() %}
        {% for message in messages %}
            <h4>{{ message }}</h4>
        {% endfor %}
    {% endwith %}

    {% block main %}{% endblock %}
</main>

</body>
</html>

templates/entries/form.html
{% extends "base.html" %}

{% block title %}Create / edit entry{% endblock %}

{% block heading %}Create / edit entry{% endblock %}

{% block main %}
<a href="{{ url_for('entries.list_all') }}">Close</a>

<form method="post">
        {{ form.csrf_token }}

            {{ form.description.label }}
            {{ form.description }}
            {% if form.description.errors %}
                <ul>
                    {% for error in form.category.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {{ form.submit(onclick='return confirm("' + ('Create' if create else 'Save') + ' entry?")') }}
    </form>

{% endblock %}

templates/entries/list.html
{% extends "base.html" %}

{% block title %}Entries{% endblock %}

{% block heading %}Entries{% endblock %}

{% block main %}

{% for entry in entries %}
    <h2>
        {{ entry.day }}
    </h2>

    <a href="{{url_for("entries.view", entry_id=entry.id)}}">View</a>
    <a href="{{ url_for("entries.edit", entry_id=entry.id) }}">Edit</a>

    <form method="post" action="{{ url_for('entries.delete', entry_id=entry.id) }}">
        <button type="submit" onclick="return confirm('Delete entry?')">
            Delete
        </button>
    </form>

    <p>
        {{ entry.description }}
    </p>
    <hr>

{% endfor %}

{% endblock %}

templates/entries/view.html
{% extends "base.html" %}

{% block title %}View entry{% endblock %}

{% block heading %}View entry{% endblock %}

{% block main %}

    <a href="{{ url_for('entries.list_all') }}">Close</a>

    <h2>
        {{ entry.day }}
    </h2>

    <p>
        {{ entry.description }}
    </p>
    <br>
    <hr>
    <form method="post">
        {{ comment_form.csrf_token }}

            {{ comment_form.username.label }}
            {{ comment_form.username }}
            {% if comment_form.username.errors %}
                <ul>
                {% for error in comment_form.username.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {{ comment_form.content.label }}
            {{ comment_form.content }}
            {% if comment_form.content.errors %}
                <ul>
                    {% for error in comment_form.content.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {{ comment_form.entry_id }}
            {{ comment_form.submit }}
    </form>

    {% for comment in entry.comments[::-1] %}
        <h3>{{ comment.username }}</h3>
         <p>{{ comment.content }}</p>
    {% endfor %}


{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}

{% block main %}
    <h2>Home</h2>
{% endblock %}